package Lab2Dmitrovskis;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * GUI class
 * @author Core_Nvidia
 */
public class GUI extends javax.swing.JFrame {
    File data;
    private Methods method = new Methods();
    private int age;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        answersArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        chooseFile = new javax.swing.JMenuItem();
        readAge = new javax.swing.JMenuItem();
        readPrintBase = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        getAverages = new javax.swing.JMenuItem();
        format = new javax.swing.JMenuItem();
        sort = new javax.swing.JMenuItem();
        remove = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        taskInfo = new javax.swing.JMenuItem();
        programInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ageField.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        ageField.setForeground(new java.awt.Color(204, 0, 0));
        ageField.setText("Write the age in here!");

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Age", "Height", "Avg. assists", "Avg. points"
            }
        ));
        jScrollPane1.setViewportView(mainTable);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Age:");

        answersArea.setColumns(20);
        answersArea.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        answersArea.setForeground(new java.awt.Color(255, 51, 51));
        answersArea.setRows(5);
        jScrollPane2.setViewportView(answersArea);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu1.setText("File");

        chooseFile.setText("Choose file");
        chooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFileActionPerformed(evt);
            }
        });
        jMenu1.add(chooseFile);

        readAge.setText("Read age");
        readAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAgeActionPerformed(evt);
            }
        });
        jMenu1.add(readAge);

        readPrintBase.setText("Read and print base");
        readPrintBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readPrintBaseActionPerformed(evt);
            }
        });
        jMenu1.add(readPrintBase);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        getAverages.setText("Average age and height");
        getAverages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAveragesActionPerformed(evt);
            }
        });
        jMenu2.add(getAverages);

        format.setText("Formatting");
        format.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatActionPerformed(evt);
            }
        });
        jMenu2.add(format);

        sort.setText("Sorting");
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });
        jMenu2.add(sort);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jMenu2.add(remove);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        taskInfo.setText("Task information");
        taskInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskInfoActionPerformed(evt);
            }
        });
        jMenu3.add(taskInfo);

        programInfo.setText("Program info");
        programInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programInfoActionPerformed(evt);
            }
        });
        jMenu3.add(programInfo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2)
                    .addComponent(ageField, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Choose file button action
     * @param evt 
     */
    private void chooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chooseRead = new JFileChooser();
        chooseRead.setDialogTitle("Open file for reading");
        chooseRead.showOpenDialog(null);
        data = chooseRead.getSelectedFile();
    }//GEN-LAST:event_chooseFileActionPerformed

    /**
     * Read age button action
     * @param evt 
     */
    private void readAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAgeActionPerformed
        // TODO add your handling code here:
        String temp;
        temp = ageField.getText();
        age = Integer.parseInt(temp);
    }//GEN-LAST:event_readAgeActionPerformed
    
    /**
     * Read and print base data button action
     * @param evt 
     */
    private void readPrintBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readPrintBaseActionPerformed
        // TODO add your handling code here:
        method.printBasePlayers(data, answersArea, mainTable);
    }//GEN-LAST:event_readPrintBaseActionPerformed
    
    /**
     * Exit button action
     * @param evt 
     */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed
    
    /**
     * Get averages button action
     * @param evt 
     */
    private void getAveragesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAveragesActionPerformed
        // TODO add your handling code here:
        answersArea.append("Found the average height and age of players!\n");
        method.printAverages(answersArea);
    }//GEN-LAST:event_getAveragesActionPerformed
    
    /**
     * Format button action
     * @param evt 
     */
    private void formatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatActionPerformed
        // TODO add your handling code here:
        method.formattingTallest();
        answersArea.append("Formed a new list with players who are taller than the average height!\n");
        method.updateTable(mainTable);
    }//GEN-LAST:event_formatActionPerformed

    /**
     * Sort button action
     * @param evt 
     */
    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        // TODO add your handling code here:
        method.sortPlayersByAgeAndName();
        answersArea.append("Players were sorted by age in ascending order and name alphabetically!\n");
        method.updateTable(mainTable);
    }//GEN-LAST:event_sortActionPerformed
    
    /**
     * Remove button action
     * @param evt 
     */
    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
        method.removePlayers(age);
        answersArea.append("Removed players who are older than the entered age!");
        method.updateTable(mainTable);
    }//GEN-LAST:event_removeActionPerformed
    
    /**
     * Task information button action
     * @param evt 
     */
    private void taskInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Krepšinio mokykloje "
                + "treniruotes lankančių sąrašas yra tekstiniame faile: būsimo "
                + "krepšininko vardas ir pavardė, amžius ir ūgis.");
    }//GEN-LAST:event_taskInfoActionPerformed
    
    /**
     * Program information button action
     * @param evt 
     */
    private void programInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Antroji programa\nVersija 1.0\nSpalis 2023", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_programInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JTextArea answersArea;
    private javax.swing.JMenuItem chooseFile;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem format;
    private javax.swing.JMenuItem getAverages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mainTable;
    private javax.swing.JMenuItem programInfo;
    private javax.swing.JMenuItem readAge;
    private javax.swing.JMenuItem readPrintBase;
    private javax.swing.JMenuItem remove;
    private javax.swing.JMenuItem sort;
    private javax.swing.JMenuItem taskInfo;
    // End of variables declaration//GEN-END:variables
}
